on:
  issue_comment:
    types: [created]

name: TEST

jobs:
  ready-for-qa:
    name: Ready For QA
    if: contains(github.event.comment.body, '/rfq')
    runs-on: ubuntu-latest
    steps:
      - name: TEST
        run: echo Ready For QA
